# Generated by Django 4.1.13 on 2023-12-21 04:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dbuserapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documents",
            old_name="doc_id",
            new_name="_id",
        ),
    ]
